version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - DATABASE_URL=postgresql://mahato:mahato@db:5432/sei_institute?schema=sample
      - JWT_SECRET=mahatohariomsfadfnasldkjf
      - ACCESS_TOKEN_EXPIRES=1d
      - REFRESH_TOKEN_EXPIRES=7d
      - NODE_ENV=dev
      - CLIENT_ENDPOINT=http://localhost:3000
    depends_on:
      - db
    command: ["sh", "-c", "npx prisma migrate deploy && npm run start:dev"]
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:9000/api/v1
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mahato
      POSTGRES_PASSWORD: mahato
      POSTGRES_DB: sei_institute
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
