version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: sei_postgres
    restart: always
    environment:
      POSTGRES_USER: sei_user
      POSTGRES_PASSWORD: strong_password_here
      POSTGRES_DB: sei_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: sei_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sei_backend
    restart: always
    depends_on:
      - postgresql
      - redis
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=9000
      - DATABASE_URL=postgresql://sei_user:strong_password_here@postgresql:5432/sei_db?schema=public
      - CLIENT_ENDPOINT=https://your-domain.com
      - JWT_SECRET=your_jwt_secret_here
      - ACCESS_TOKEN_EXPIRES=1d
      - REFRESH_TOKEN_EXPIRES=7d
      - HUGGING_FACE_KEY=${HUGGING_FACE_KEY}
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sei_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.your-domain.com
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: sei_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: 