export const apiKeys = {
  login: "login",
  logout: "logout",
  register: "register",
  completeProfile: "completeProfile",
  getProfile: "getProfile",
  contact: "contact",
  getAllSubjects: "getAllSubjects",
  enrollInSubject: "enrollInSubject",
  getEnrolledCourses: "getEnrolledCourses",
  getUserDetails: "getUserDetails",
  updateUser: "updateUser",
  updateUserProfilePic: "updateUserProfilePic",
  unenrollFromSubject: "unenrollFromSubject",
  userCourses: "userCourses",
  practise: {
    getAll: "practise:getAll",
    create: "practise:create",
    update: "practise:update",
    delete: "practise:delete",
    history: "practise:history",
  },

  pdfs: {
    getAll: "pdfs:getAll",
    upload: "pdfs:upload",
    download: "pdfs:download",
    bulkDownload: "pdfs:bulkDownload",
    delete: "pdfs:delete",
  },
  admin: {
    getAllUsers: "admin:getAllUsers",
    deleteUser: "admin:deleteUser",
    getAllContacts: "admin:getAllContacts",
    editContact: "admin:editContact",
    deleteContact: "admin:deleteContact",
    getAllSubjects: "admin:getAllSubjects",
    createSubject: "admin:createSubject",
    editSubject: "admin:editSubject",
    deleteSubject: "admin:deleteSubject",

    getAllCarousels: "admin:getAllCarousels",
    updateCarousel: "admin:updateCarousel",
    deleteCarousel: "admin:deleteCarousel",
    createCarousel: "admin:createCarousel",
  },
};
