export const apiKeys = {
  login: "login",
  logout: "logout",
  register: "register",
  completeProfile: "completeProfile",
  getProfile: "getProfile",
  contact: "contact",
  getAllSubjects: "getAllSubjects",
  enrollInSubject: "enrollInSubject",
  getEnrolledCourses: "getEnrolledCourses",
  getUserDetails: "getUserDetails",
  updateUser: "updateUser",
  updateUserProfilePic: "updateUserProfilePic",
  unenrollFromSubject: "unenrollFromSubject",
  userCourses: "userCourses",

  admin: {
    getAllUsers: "admin:getAllUsers",
    deleteUser: "admin:deleteUser",
    getAllContacts: "admin:getAllContacts",
    editContact: "admin:editContact",
    deleteContact: "admin:deleteContact",
    getAllSubjects: "admin:getAllSubjects",
    createSubject: "admin:createSubject",
    editSubject: "admin:editSubject",
    deleteSubject: "admin:deleteSubject",
  },
};
